version: "3.8"

services:
  twingate:
    build: ./twingate
    restart: always
    volumes:
      # Mount the service key into the container
      - ./service_key.json:/etc/twingate/service_key.json:ro
    network_mode: "host"
